config/routes.rb
Rails.application.routes.draw do
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"

  resources :users
  

  resources :posts do
    resources :likes, only: [:index, :create, :destroy]
  end

  
  

  root 'home#index'
  resources :home, only: [:index, :show]
  
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, {presence: true}
  validates :post_id, {presence: true}

  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def index
    @likes = Like.where(user_id: @current_user.id)
  end

  def create
    @like = Like.new(
      user_id: @current_user.id,
      post_id: @post.id
    )
    @like.save
  end

  def destroy
    @like = Like.find_by(
      user_id: @current_user.id,
      post_id: @post.id
    )
    @like.destroy
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/views/likes/_like.html.haml
-if Like.find_by(user_id: @current_user.id, post_id: @post.id)
  = link_to(post_like_path(@post, post.id), method: :delete, remote: true) do
    %li.optionalBtn.already
      .like-heart
        = icon('fa', 'heart')
        = Like.where(post_id: @post.id).count
-else 
  = link_to(post_likes_path(@post), method: :post, remote: true) do
    %li.optionalBtn.none
      .like-heart
        = icon('fa', 'heart')
        = Like.where(post_id: @post.id).count
  

app/views/likes/create.js.erb
$('#likeBtn').html("<%= j(render partial: 'likes/like', locals: { post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likeBtn').html("<%= j(render partial: 'likes/like', locals: { post: @post}) %>");

app/views/likes/index.html.haml
.main.posts-index
  .container
    - if @likes.present?
      %ul
        - @likes.each do |like|
          %li
            = link_to post_path(like.post.id) do
              .posts-index-item
                .post-left
                  = image_tag like.post.user.image.url
                .post-right
                  .post-user-name
                    = like.post.user.nickname
                  = like.post.content